"""add_context_window_to_config

Revision ID: 58cf9063fe3f
Revises: ac00f878b352
Create Date: 2025-10-08 16:51:42.615298
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58cf9063fe3f"
down_revision = "ac00f878b352"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("configs", sa.Column("context_window", sa.Integer(), nullable=True))
    op.alter_column(
        "configs",
        "system_prompt",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "configs",
        "system_prompt",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("configs", "context_window")
    # ### end Alembic commands ###
