"""Add artifact deduplication with sha256

Revision ID: 980ae8fe2fe4
Revises: 58cf9063fe3f
Create Date: 2025-10-16 16:20:57.897479
"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "980ae8fe2fe4"
down_revision = "58cf9063fe3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artifacts", sa.Column("sha256", sa.String(length=64), nullable=False)
    )
    op.add_column(
        "artifacts", sa.Column("filename", sa.String(length=512), nullable=False)
    )
    op.add_column("artifacts", sa.Column("mime", sa.String(length=128), nullable=False))
    op.add_column("artifacts", sa.Column("size", sa.Integer(), nullable=False))
    op.add_column(
        "artifacts", sa.Column("session_id", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "artifacts", sa.Column("run_id", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "artifacts", sa.Column("tool_call_id", sa.String(length=128), nullable=True)
    )
    op.create_index(op.f("ix_artifacts_sha256"), "artifacts", ["sha256"], unique=False)
    op.create_index(
        "ix_artifacts_thread_created",
        "artifacts",
        ["thread_id", "created_at"],
        unique=False,
    )
    op.drop_column("artifacts", "type")
    op.drop_column("artifacts", "uri")
    op.drop_column("artifacts", "blob")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artifacts",
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "artifacts",
        sa.Column("uri", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    )
    op.add_column(
        "artifacts",
        sa.Column("type", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_artifacts_thread_created", table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_sha256"), table_name="artifacts")
    op.drop_column("artifacts", "tool_call_id")
    op.drop_column("artifacts", "run_id")
    op.drop_column("artifacts", "session_id")
    op.drop_column("artifacts", "size")
    op.drop_column("artifacts", "mime")
    op.drop_column("artifacts", "filename")
    op.drop_column("artifacts", "sha256")
    # ### end Alembic commands ###
